version: "3"
services:
  nats:
    image: nats:2.10
    ports:
      - "4222:4222"
      - "8222:8222"
  nui:
    image: ghcr.io/nats-nui/nui:edge
    volumes:
      - ./db:/db
    ports:
      - "31312:31311"
    depends_on:
      - nats