name: desktop build

on:
  push:
    tags:
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    permissions: write-all
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'nui-linux-amd64'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'nui-windows-amd64.exe'
            platform:  'windows/amd64'
            os: 'windows-latest'
            nsis: true
          - name: 'nui-macOS-universal'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          app-working-directory: 'nui-desktop'
          package: false
          go-version: '1.21'
          nsis: ${{ matrix.build.nsis }}
      # Upload build assets
      - uses: actions/upload-artifact@v3
        with:
          name: nui-${{runner.os}}-${{matrix.build.name}}
          path: |
            nui-desktop/build/bin/
            nui-desktop\build\bin\*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nui-desktop/build/bin/*
          
