name: desktop build

on:
  push:
    tags:
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build_and_test:
    uses: ./.github/workflows/build-and-test.yml
  release:
    needs: [build_and_test]
    permissions: write-all
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'nui-app'
            platform_name: 'linux-amd64'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'nui-app'
            platform_name: 'windows-amd64'
            platform:  'windows/amd64'
            os: 'windows-latest'
            nsis: true
          - name: 'nui-app'
            platform_name : 'macOS'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.21'
          nsis: ${{ matrix.build.nsis }}
      - name: rename artifacts linux
        if : ${{ matrix.build.platform_name == 'linux-amd64' }}
        run: |
          mv build/bin/nui-app build/bin/${{ matrix.build.platform_name }}-nui-app
      - name: rename artifacts windows
        if : ${{ matrix.build.platform_name == 'windows-amd64' }}
        run: |
          mv build/bin/nui-app build/bin/${{ matrix.build.platform_name }}-nui-app.exe
          mv build/bin/nui-app-amd64-installer.exe build/bin/${{ matrix.build.platform_name }}-nui-app-installer.exe
      - name : rename artifacts macOS
        if : ${{ matrix.build.platform_name == 'macOS' }}
        run: |
          mv build/bin/nui-app.app.zip build/bin/${{ matrix.build.platform_name }}-nui-app.app.zip
          mv build/bin/nui-app.pkg build/bin/${{ matrix.build.platform_name }}-nui-app.pkg

      # Upload build assets
      - uses: actions/upload-artifact@v3
        with:
          name: nui-${{runner.os}}-${{matrix.build.name}}
          path: |
            build/bin/
            build\bin\*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/bin/*
          
